table cotacoes
	lineageTag: 59cc2475-48ed-4ca4-b466-f07737a440c8

	measure 'Cotação do dia' = AVERAGE(cotacoes[Cotacao])
		displayFolder: Medidas
		lineageTag: 35490143-a20c-4fb9-a9a1-f1e4b83e5c70

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			
			```
		displayFolder: Medidas
		lineageTag: c14e7400-40bf-4235-874a-1d1e579be133

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 99747e9e-5492-4963-9019-4e479654e1f2
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column DataHora
		dataType: dateTime
		formatString: General Date
		displayFolder: Colunas
		lineageTag: f88491fa-54f3-4142-b875-668e5339bd8d
		summarizeBy: none
		sourceColumn: DataHora

		annotation SummarizationSetBy = Automatic

	column Cotacao
		dataType: double
		displayFolder: Colunas
		lineageTag: c3204090-37d0-49c3-89ad-775212a68d3a
		summarizeBy: average
		sourceColumn: Cotacao

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TipoBoletim
		dataType: string
		displayFolder: Colunas
		lineageTag: 12ff5560-ce42-4d3a-a01d-16267dfd6376
		summarizeBy: none
		sourceColumn: TipoBoletim

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: dd/mm/yy
		displayFolder: Colunas
		lineageTag: b84b7ee8-0aa2-4d6c-a6d6-3e75d1360770
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition cotacoes = m
		mode: import
		queryGroup: Fatos
		source = getCotacoes(data_inicial, data_final)

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

